# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ef9336f1641567b44cd55c4ace0ee298f55b5aff2ed93d35bdddbdf17843183dc3c73e2ad383e613f833d09882d572605a8ad995a9427a96126bbacda510d25

test:
  secret_key_base: fe4e725be83618870886ae3f0a1716314ebab9a087d55e4273dacc83a2f2d67e6aec522f68ee3d8f781ca36373633b6912407ca11c46a23208f98b1c33d90137

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
